name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'PDF Compressor v__VERSION__'
          releaseBody: |
            ## What's New
            
            ### Features
            - Professional PDF compression with multiple quality presets
            - Built-in PDF optimization engine (no external dependencies)
            - Modern, minimalist user interface
            - Cross-platform support (Windows, macOS, Linux)
            
            ### Technical Details
            - Screen: 72 DPI, JPEG quality 30% - optimal for web sharing
            - eBook: 150 DPI, JPEG quality 50% - balanced quality and size
            - Printer: 300 DPI, JPEG quality 80% - high quality for printing
            - Prepress: 300+ DPI, JPEG quality 90%+ - professional printing standard
            
            ### Installation
            - **Windows**: Download and run the `.msi` or `.exe` installer
            - **macOS**: Download the `.dmg` file and drag to Applications
            - **Linux**: Download the `.AppImage` or `.deb` file
            
            ---
            
            🚀 Built with Tauri, React, and Rust for optimal performance and security.
          releaseDraft: true
          prerelease: false
          args: --verbose